name: wireguard-dtp
version: '1.0.20210914'
summary: Fast, modern, secure kernel VPN tunnel
description: |
  Fast, modern, secure kernel VPN tunnel

base: core24
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

layout:
  /etc/wireguard:
    bind: $SNAP_DATA/etc

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

apps:
  wireguard:
    plugs: [firewall-control, network, network-bind, network-control]
    command: bin/start.sh
    start-timeout: 120s
    stop-command: bin/stop.sh
    stop-timeout: 120s
    daemon: oneshot
  wg:
    plugs: [firewall-control, network, network-bind, network-control]
    command: usr/bin/wg
  wg-quick:
    plugs: [firewall-control, network, network-bind, network-control]
    command: usr/bin/wg-quick

parts:
  local:
    plugin: dump
    source-type: local
    source: snap/local
  wireguard:
    plugin: nil
    stage-packages:
      - wireguard
    stage:
      - usr/bin/wg
      - usr/bin/wg-quick
