name: wireguard-dtp
version: '1.0.20210914'
summary: Fast, modern, secure kernel VPN tunnel
description: |
  Fast, modern, secure kernel VPN tunnel

base: core24
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

layout:
  /etc/wireguard:
    bind: $SNAP_DATA/etc

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

apps:
  wireguard:
    command: bin/start.sh
    start-timeout: 120s
    stop-command: bin/stop.sh
    stop-timeout: 120s
    daemon: oneshot
    plugs: [firewall-control, network, network-bind, network-control]
  wg:
    command: bin/wg
    plugs: [firewall-control, network, network-bind, network-control]
  wg-quick:
    command: bin/wg-quick
    plugs: [firewall-control, network, network-bind, network-control]

parts:
  wireguard:
    plugin: dump
    source-type: local
    source: snap/local
    stage-packages:
      - wireguard
    override-prime: |
      craftctl default
      cp usr/bin/wg bin
      cp usr/bin/wg-quick bin
      rm -rf etc
      rm -rf lib
      rm -rf usr
      rm -rf var
